name: corp_devices
description: Project for managing Android & iOS devices with CORP

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: 1.1.1
  collection: 1.17.2
  connectivity_plus: 5.0.1
  cupertino_icons: 1.0.5
  device_info: 2.0.2
  diacritic: 0.1.3
  dio: 4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_loggy_dio: 2.0.0+3
  flutter_native_splash: 2.2.8
  flutter_riverpod: 2.0.0
  flutter_sheet_localization: null
  flutter_sticky_header: 0.6.4
  flutter_svg: 1.1.3
  freezed_annotation: 2.1.0
  go_router: 12.1.0
  hive: 2.0.4
  hive_flutter: 1.1.0
  http: 0.13.4
  intl: 0.18.1
  json_annotation: 4.5.0
  json_serializable: 6.2.0
  loggy: 2.0.1+1
  lottie: 1.4.2
  modal_bottom_sheet: 2.1.2
  package_info_plus: 4.2.0
  pretty_dio_logger: 1.2.0-beta-1
  qr_flutter: 4.0.0
  scan: 1.6.0
  url_strategy: ^0.2.0

dependency_overrides:
  http: 0.13.0
  intl: 0.18.1
  modal_bottom_sheet: ^3.0.0-pre
  analyzer: null

dev_dependencies:
  build_runner: 2.2.0
  flutter_gen_runner: 4.3.0
  flutter_lints: 2.0.1

  flutter_sheet_localization_generator: null

  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  hive_test: 1.0.1
  http_mock_adapter: 0.3.3

  # tests
  integration_test:
    sdk: flutter

  mocktail: ^1.0.1

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

flutter:
  uses-material-design: true
  fonts:
    - family: GintoNord
      fonts:
        - asset: assets/fonts/GintoNord-Black.otf
    - family: Ginto
      fonts:
        - asset: assets/fonts/GintoNormal-Regular.otf
        - asset: assets/fonts/GintoNormal-Bold.otf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/json/
    - assets/splash/

flutter_native_splash:
  background_image: assets/splash/splash.png
  ios_content_mode: scaleAspectFit
  web: false
